experiment_name: ???
data_path: ???
training_path: training/
eval_path: results/
mixed_precision : false

log_dir: ../outputs/${experiment_name}/${now:%Y-%m-%d}/${now:%H-%M-%S}

hydra:
  run:
    dir: ${log_dir}

