defaults:
  - hydra
  - train
  - models/two_view_pipeline@model
  - models/extractors/superpoint_open@model.extractor
  - models/matchers/homography@model.ground_truth
  - models/matchers/lightglue@model.matcher
  - data/homography@data

train:
  seed: 0
  epochs: 40
  log_every_iter: 100
  eval_every_iter: 500
  lr: 1e-4
  lr_schedule:
    start: 20
    type: exp
    on_epoch: true
    exp_div_10: 10
  plot:
    - 5
    - _target_: gluefactory.visualization.visualize_batch.make_match_figures
model:
  extractor:
    max_num_keypoints: 512
    force_num_keypoints: true
    detection_threshold: -1
    nms_radius: 3
    trainable: false
  ground_truth:
    th_positive: 3
    th_negative: 3
  matcher:
    filter_threshold: 0.1
    flash: false
    checkpointed: false
data:
  train_size: 150000
  val_size: 2000
  batch_size: 128
  num_workers: 14
  homography:
    difficulty: 0.7
    max_angle: 45
  photometric:
    name: lg